name: NekogramX

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    if: "!endsWith(github.event.head_commit.message, '~')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup ghr
        run: |
          wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          tar xvzf ghr.tar.gz; rm ghr.tar.gz
          sudo mv ghr*linux_amd64/ghr /usr/local/bin; rm -rf ghr*linux_amd64
      - name: assemble
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
        run: |
          ./gradlew assembleRelease
          ./gradlew assembleReleaseNoGcm
      - name: Upload apks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir apks; find . -name "*.apk" -exec mv {} apks \;
          ghr -n "Build $GITHUB_SHA" -b "${{ github.event.head_commit.message }}" -prerelease -delete latest apks/