name: NekogramX

on:
  push:
    branches:
      - master
      - release

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: assembleAfatRelease
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
        run: |
          ./gradlew assembleRelease assembleReleaseNoGcm
          OUTPUT="TMessagesProj/build/outputs"
          echo ::set-env name=APK_FILE::$(find $OUTPUT/apk/afat/release -name "*.apk")
      - name: bundleAfatRelease
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
        run: |
          export KEYSTORE_PASS ALIAS_NAME ALIAS_PASS
          ./gradlew bundleAfatRelease
          OUTPUT="TMessagesProj/build/outputs"
          echo ::set-env name=AAB_FILE::$(find $OUTPUT/bundle -name "*.aab")
        if: github.ref == 'refs/heads/release'
      - uses: NekogramX/nekox-build-script@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          RELEASE_CHANNEL:  ${{ secrets.RELEASE_CHANNEL }}
          CANARY_CHANNEL:  ${{ secrets.CANARY_CHANNEL }}
      - uses: actions/upload-artifact@master
        with:
          name: NekoX-${{ github.sha }}.zip
          path: "TMessagesProj/build/outputs"
        if: github.ref == 'refs/heads/master'
      - uses: r0adkll/upload-google-play@master
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_ACCOUNT_SERVICE }}
          packageName: nekox.messenger
          releaseFile: ${{ env.AAB_FILE }}
          track: production
          whatsNewDirectory: whatsnew
        if: github.ref == 'refs/heads/release'