name: NekogramX

on:
  push:
    branches:
      - master
      - release

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, ':B:')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: setup-ghr
        run: |
          wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          tar xvzf ghr.tar.gz; rm ghr.tar.gz
          sudo mv ghr*linux_amd64/ghr /usr/local/bin; rm -rf ghr*linux_amd64
      - name: assembleRelease
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
        run: |
          ./gradlew assembleAfatRelease
          echo ::set-env name=APK_FILE::$(find TMessagesProj/build/outputs/apk/afat/release -name "*.apk")
      - uses: NekogramX/nekox-build-script@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          RELEASE_CHANNEL:  ${{ secrets.RELEASE_CHANNEL }}
          CANARY_CHANNEL:  ${{ secrets.CANARY_CHANNEL }}
      - name: Upload apks
        run: |
          mkdir apks; find . -name "*.apk" -exec mv {} apks \;
          git push origin :latest | echo "Previous build not found"
          git tag latest
          git push origin latest
          ghr -n "Build $GITHUB_SHA" \
            -c "$GITHUB_SHA"
            -b ${{ github.event.head_commit.message }} \
            --prerelease --delete latest apks/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
