name: NekogramX

on:
  push:
    branches:
      - master
      - release

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, ':B:')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: assembleRelease
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
        run: |
          ./gradlew assembleAfatRelease
          echo ::set-env name=APK_FILE::$(find TMessagesProj/build/outputs/apk/afat/release -name "*.apk")
      - uses: NekogramX/nekox-build-script@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          RELEASE_CHANNEL:  ${{ secrets.RELEASE_CHANNEL }}
          CANARY_CHANNEL:  ${{ secrets.CANARY_CHANNEL }}
      - name: Find apks
        run: mkdir apks; find . -name "*.apk" | xargs -0 -I {} mv {} apks
      - name: Upload apks
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: apks/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}