name: NekogramX

on:
  push:
    branches:
      - master
      - release

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
        run: |
          ./gradlew assembleAfatRelease
          ./gradlew bundleAfatRelease
      - name: Find artifact files
        run: |
          OUTPUT="TMessagesProj/build/outputs"
          echo ::set-env name=APK_FILE::$(find $OUTPUT/apk -name "*.apk")
      - name: Find aab file
        run: |
          OUTPUT="TMessagesProj/build/outputs"
          echo ::set-env name=AAB_FILE::$(find $OUTPUT/bundle -name "*.aab")
        if: github.ref == 'refs/heads/release'
      - uses: NekogramX/nekox-build-script@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          RELEASE_CHANNEL:  ${{ secrets.RELEASE_CHANNEL }}
          CANARY_CHANNEL:  ${{ secrets.CANARY_CHANNEL }}
      - uses: actions/upload-artifact@master
        with:
          name: NekoX-${{ github.sha }}.apk
          path: ${{ env.APK_FILE }}
        if: github.ref == 'refs/heads/master'
      - uses: r0adkll/upload-google-play@v1.0.4
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_ACCOUNT_SERVICE }}
          packageName: moe.wataru.nekogram
          releaseFile: ${{ env.AAB_FILE }}
          track: production
          whatsNewDirectory: whatsnew
        if: github.ref == 'refs/heads/release'