name: Canary Build

on:
  push:
    branches:
      - master

jobs:
  canaryBuild:
    name: Canary Build
    runs-on: ubuntu-latest
    if: "!endsWith(github.event.head_commit.message, '~')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: assembleAfatCanary
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
        run: |
          ./gradlew assembleAfatCanary
          echo ::set-env name=APK_FILE::$(find TMessagesProj/build/outputs/apk -name "*.apk")
      - uses: NekogramX/nekox-build-script@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          RELEASE_CHANNEL:  ${{ secrets.RELEASE_CHANNEL }}
          CANARY_CHANNEL:  ${{ secrets.CANARY_CHANNEL }}